// CopyRight FlareHorz Team. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "ModuleInterface.h"

using UModuleInitializer = IModuleInterface* (*)();

/**
 * Implements the module manager.
 *
 * The module manager is used to load and unload modules, as well as to keep track of all the
 * modules that are currently loaded. You can access this singleton using CModuleManager::Get().
 */
class CModuleManager
{
	struct SPrivateToken { explicit SPrivateToken() = default; };
	
public:
	/**
	 * Hidden constructor.
	 *
	 * Use the static Get() function to return the singleton instance.
	 */
	CORE_API CModuleManager(SPrivateToken) { }

	// Disallow copying
	CModuleManager(const CModuleManager&) = delete;
	CModuleManager& operator=(const CModuleManager&) = delete;

	/** Gets the singleton instance of the module manager. */
	static CORE_API CModuleManager& Get();
	
	/**
	 * Loads the specified module unless it was already loaded.
	 *
	 * @param InModuleName The name of the module.
	 * @return The loaded module, or nullptr if the load operation failed.
	 */
	CORE_API IModuleInterface* LoadModule(const CString& InModuleName);

	/**
	 * Loads the specified module unless it was already loaded, checking to ensure it's valid.
	 * 
	 * @param InModuleName The name of the module.
	 * @return The loaded module, or nullptr if the load operation failed.
	 */
	CORE_API IModuleInterface* LoadModuleChecked(const CString& InModuleName);

	/**
	 * Gets the specified module.
	 *
	 * @param InModuleName Name of the module to return.
	 * @return The module, or nullptr if the module is not loaded.
	 */
	CORE_API IModuleInterface* GetModule(const CString& InModuleName);

	/**
	 * Unloads modules during the shutdown process. Modules are unloaded in reverse order to when their StartupModule() FINISHES.
	 * The practical implication of this is that if module A depends on another module B, and A loads B during A's StartupModule, 
	 * that B will actually get Unloaded after A during shutdown. This allows A's ShutdownModule() call to still reference module B.
	 * You can manually unload a module yourself which will change this ordering, but be careful as you may be unloading another module's dependency!
	 *
	 * This method is usually called at various points while exiting an application.
	 */
	CORE_API void UnloadModulesAtShutdown();

	/**
	 * Unloads a specific module.
	 * NOTE: You can manually unload a module before the normal shutdown occurs with this,
	 * but be careful as you may be unloading another module's dependency too early!
	 */
	CORE_API void UnloadModule(const CString& InModuleName);

	/** Checks whether the specified module is currently loaded. */
	CORE_API bool IsModuleLoaded(const CString& InModuleName) const;

	/** Gets the number of currently loaded modules. */
	CORE_API int32 GetModuleCount() const;

	/**
	 * Adds a module to our list of modules, unless it's already known.
	 * 
	 * This method is intended for internal use only and is called automatically
	 * by the IMPLEMENT_MODULE() macro during static initialization. It typically should not be invoked manually.
	 *
	 * @param InModuleName Name of the module. Passed as a TCHAR string because the value is generated by preprocessor macro.
	 * @param ModuleInitializer A static function or lambda that should return a valid pointer to the IModuleInterface.
	 */
	CORE_API void AddModule_Internal(const TCHAR* InModuleName, const UModuleInitializer& ModuleInitializer);

private:
	/**
	 * Information about a single module (may or may not be loaded).
	 */
	class CModuleInfo
	{
	public:
		CModuleInfo(IModuleInterface* InInterface)
			: Interface(InInterface)
			, LoadOrder(CurrentLoadOrder++)
		{ }

		~CModuleInfo() = default;
		
		/** Handle to this module (DLL handle), if it's currently loaded. */
		void* Handle;

		/** The module object for this module. We actually *own* this module, so it's lifetime is controlled by the scope of this shared pointer. */
		TUniquePtr<IModuleInterface> Interface;

		/** True if this module was unloaded at shutdown time, and we never want it to be loaded again. */
		bool bWasUnloadedAtShutdown = false;

		/** True if this module is full loaded and ready to be used */
		bool bIsReady = false;

		/** Arbitrary number that encodes the load order of this module, so we can shut them down in reverse order. */
		int32 LoadOrder;
		
		/** Tracks the current load number. Incremented whenever we add a new module. */
		static int32 CurrentLoadOrder;
	};
	
	/** List of all modules that are currently loaded. */
	TMap<CString, TSharedPtr<CModuleInfo>> Modules;

	/** Finds a module that corresponds to a specified module name. */
	TSharedPtr<CModuleInfo> FindModule(const CString& InModuleName) const;
};

/**
 * A default minimal implementation of a module that does nothing at startup and shutdown.
 */
class CDefaultModuleImpl final : public IModuleInterface
{
	// ...
};

namespace FH::Core::Private
{
	constexpr bool ModuleNameEquals(const char* Lhs, const char* Rhs)
	{
		for (;;)
		{
			if (*Lhs != *Rhs) return false;
			if (*Lhs == '\0') return true;
			++Lhs;
			++Rhs;
		}
	}
}

/**
 * Module implementation boilerplate for regular modules.
 * Should be placed in source file rather than header because if it's not included anywhere the module will not get registered.
 */
#define IMPLEMENT_MODULE( ModuleImplClass, ModuleName ) \
	extern "C" static IModuleInterface* Z_Initialize##ModuleName##Module() \
	{ \
		return new ModuleImplClass(); \
	} \
	class Z_C_##ModuleName##_ModuleRegistrator final \
	{ \
	public: \
		Z_C_##ModuleName##_ModuleRegistrator(const TCHAR* Name, const UModuleInitializer& ModuleInitializer) \
		{ \
			static_assert(FH::Core::Private::ModuleNameEquals(#ModuleName, FH_STRINGIZE(FH_MODULE_NAME)), "Module name mismatch (" #ModuleName " != " FH_STRINGIZE(FH_MODULE_NAME) \
				"). Please ensure module name passed to IMPLEMENT_MODULE is " FH_STRINGIZE(FH_MODULE_NAME) "!"); \
			CModuleManager::Get().AddModule_Internal(Name, ModuleInitializer); \
		} \
	}; \
	static Z_C_##ModuleName##_ModuleRegistrator Z_##ModuleName##_ModuleRegistrator(TEXT(#ModuleName), Z_Initialize##ModuleName##Module);
